# Generated by Django 5.0.6 on 2024-06-13 23:36

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='travel_plan',
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('historical', 'Historical'), ('museum', 'Museum'), ('park', 'Park'), ('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='visit',
            name='duration',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='start_place_latitude',
            field=models.FloatField(validators=[api.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='start_place_longitude',
            field=models.FloatField(validators=[api.validators.validate_longitude]),
        ),
    ]
