# Generated by Django 5.0.6 on 2024-06-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_place_travel_plan_place_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
