# Generated by Django 5.0.6 on 2024-06-16 21:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_itinerary_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
