# Generated by Django 5.0.6 on 2024-06-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_visit_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='geometry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
