# Generated by Django 5.0.6 on 2024-06-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_itinerary_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='geometry',
        ),
    ]
