# Generated by Django 5.0.6 on 2024-06-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_visit_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(),
        ),
    ]
