# Generated by Django 5.0.6 on 2024-06-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_itinerary_end_date_alter_itinerary_start_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('name', 'latitude', 'longitude')},
        ),
    ]
