# Generated by Django 5.0.6 on 2024-06-18 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_place_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('geometry', models.TextField()),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_routes', to='api.itinerary')),
            ],
            options={
                'ordering': ['itinerary', 'day'],
                'unique_together': {('itinerary', 'day')},
            },
        ),
    ]
