# Generated by Django 5.0.6 on 2024-06-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_dailyroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('historical', 'Historical'), ('museum', 'Museum'), ('park', 'Park'), ('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('shopping', 'Shopping'), ('tourist_attraction', 'Tourist attraction'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
