# Generated by Django 5.0.6 on 2024-06-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_place_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('ART', 'Art'), ('ART_GALLERY', 'Art Gallery'), ('FOUNTAIN', 'Fountain'), ('MUSEUM', 'Museum'), ('NATURE_RESERVE', 'Nature Reserve'), ('STADIUM', 'Stadium'), ('TOURIST_ATTRACTION', 'Tourist Attraction'), ('PARK', 'Park'), ('ZOO', 'Zoo'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
